### ISSUE TITLE
Improvement question : Multi engine capabilities.

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#224]
Before using all the azure tools for mobile apps (backend, this library, etc) I used other web technologies that allowed me to develop cordova apps and also webapps seamlessly. I did two projects with [PouchDb](https://github.com/pouchdb/pouchdb) and it worked great in web, android and windows phone. It just uses fallbacks in case the preferred engine is not present.

I know that JsClient uses Sqlite as backend, specially on this line:
` var db = window.sqlitePlugin.openDatabase(...`

You guys know this project way more than I do (i'm just starting to read the code). So my question is

Would it be too much work to implement something like [AnySql](https://github.com/object-layer/anysql) or [NodeWebsql](https://github.com/nolanlawson/node-websql) as a layer to interact with the database? Even adding engines as "plugins" and do the abstractions "by hand" would be fine.

Offline capabilities are great tool for online webapps as well, since it can be used as cache or anything.

Cheers

**Comment by andreujuanc** [comment]
Tried to hook Chrome's websql but no luck since there are some statements, like PRAGMA that WebSql does not support. xP Was good try tho xD

```
 window.sqlitePlugin.openDatabase =  function(options, success, callback )
    {        
        var db = openDatabase(options.name , '1.0', 'Offline document storage', 5*1024*1024, 
        function(a) {
            console.log('le callback', a);
        });

        console.log('got db', db);
        
        setTimeout(function(){
            success();
        }, 100);
        
        return db;

    };
```

**Comment by shrishrirang** [comment]
@andreujuanc: `MobileServiceSyncContext` is designed to be able to work with arbitrary store implementations. https://github.com/Azure/azure-mobile-apps-js-client/blob/2d1f6a42a6063b79e9e7deaba7c2869d07e35ad1/sdk/src/sync/MobileServiceSyncContext.js#L86 defines the initialize method that initializes the sync context with any store implementation you provide.

`MobileServiceSqliteStore` is a sqlite store based implementation provided out of the box, but you can implement a websql based store and use it. Because of the similarity between the cordova-sqlite-storage plugin and websql API, I'd suggest starting with `MobileServiceSqliteStore`, modify it to work with WebSql wherever necessary and then refactor `MobileServiceSqliteStore.js` to share the common parts with websql based store.

**Comment by andreujuanc** [comment]
Thanks for the answer, really helped me understand the project. Since i cant invest too much time on it, these kind of answers reduces lots of time reading code to understand it deeply.
