### ISSUE TITLE
Cannot use library as a require'd library

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#80]
You cannot use this library in a browserify / webpack environment.  Need to create this as a UMD library and test with CommonJS and AMD patterns.

**Comment by adrianhall** [comment]
Released in v2.0.0-beta5

**Comment by joewood** [comment]
What's the recommended approach for webpack/browserify? Requiring the distribution files seems wrong as these are prebundled. Requiring the **src/index.js** doesn't work in beta5 because it fails at requiring Platform and some queryjs modules.

**Comment by shrishrirang** [comment]
Requiring src/index.js won't work out of the box at this point because of the use of browserify aliases. 'Platforms' is defined conditionally at build time mainly to work around browserify's limitation around conditional inclusions. This will be fixed eventually. I will need to check what is the issue with queryjs modules.

Is there any specific concern you have with using the distributed bundle? Is it the size?

**Comment by joewood** [comment]
Only the usual concern that modules in this bundle won't be de-duped with the same modules used in the consuming application, or conflicts highlighted. Webpack warns to that effect. I guess this isn't a big deal at the moment, as there doesn't seem to be any real dependencies for this library. So I guess it's OK to live with the warning. 

I'll take a look at the source level errors to see if I can work around them with some aliasing etc...
